<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <script>
        let cadastro = [
            {
                nome: "João",
                idade: 25,
                email: "joao@email.com"
            },
            {
                nome: "Pedro",
                idade: 33,
                email: "pedro@email.com"
            },
            {
                nome: "Marcos",
                idade: 16,
                email: "marcos@email.com"
            }
        ];

        class UserNotFound extends Error {
            constructor(message) {
                super(message);
                this.name = "UserNotFound";
            }
        }

        function obtemUsuarioPeloNome(nome) {
            return new Promise((resolve, reject) => {
                let usuario = cadastro.find(pessoa => pessoa.nome === nome);
                if(!usuario) {
                    reject(new UserNotFound("Usuário não cadastrado!"));
                } else {
                    resolve(usuario)
                }
            })
        }

        obtemUsuarioPeloNome("Pedro")
            .then(usuario => console.log(`Usuário encontrado:\nNome: ${usuario.nome}\nIdade: ${usuario.idade}\nE-mail: ${usuario.email}`))
            .catch(error => console.log(`Erro: ${error.message}`))

    </script>
</body>
</html>